spring:
  datasource:
    # Update the URL with your database server host and name
    url: jdbc:mysql://localhost:3306/food_db
    username: root
    password: "{cipher}1d73da252730de0893876841a07d245792c9cff0f7747c735cc2e95d85f44507"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # Options: create, create-drop, validate, update
      ddl-auto: update
    show-sql: true # Prints SQL statements to the console for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Configure the Eureka Client Properities to get register to the eureka server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

server:
  port: 8080
