spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/restaurant_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

info:
  app:
    name: restaurant-service
    description: Restaurant microservice for managing menus and orders
    version: 1.0.0 Development
  developer:
    name: Zohaib_Anwar
    email: dakrsoul584@gmail.com21233kcx bhi.......
